type CategoryCount {
  category: String!
  count: Int!
}

type Document {
  file: String!
  title: String!
}

type Publication {
  id: ID!
  highlights: [String!]!
  type: String!
  categories: [String!]!
  jnr: [String!]!
  title: String!
  abstract: String
  published_date: String!
  date: String!
  is_board_ruling: Boolean!
  is_brought_to_court: Boolean!
  authority: String!
  body: String
  documents: [Document!]
}

type PublicationResponse {
  totalCount: Int!
  elapsedMilliseconds: Int!
  categoryCounts: [CategoryCount!]!
  publications: [Publication!]!
}

type Category {
  id: ID!
  title: String!
}

input QueryRequestInput {
  categories: [CategoryInput!]!
  query: String!
  sort: String!
  types: [String!]!
  skip: Int!
  size: Int!
}

input CategoryInput {
  id: ID!
  title: String!
}

type Mutation {
  scrapePublications: PublicationResponse!
}

type Query {
  fetchPublication(id: String!): Publication!
}
